# Generated by Django 2.0.3 on 2018-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('address', models.CharField(max_length=56, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
                'db_table': 'accounts',
            },
        ),
    ]
